app/lib/models/api.py
from app import db
import datetime


class ApiKeys(db.Model):
    __tablename__ = 'api_keys'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, default=0, index=True)
    name = db.Column(db.String, default='', nullable=True)
    apikey = db.Column(db.String, default='', nullable=True)
    enabled = db.Column(db.Boolean, default=False, index=True, nullable=True)
    created_at = db.Column(db.DateTime, nullable=True, default=datetime.datetime.now())

app/lib/models/config.py
from app import db


class ConfigModel(db.Model):
    __tablename__ = 'config'
    name = db.Column(db.String, default='', primary_key=True)
    value = db.Column(db.Text, default='')

app/controllers/api.py
from flask import Blueprint, Response
from app.lib.api.sessions import ApiSession
from app.lib.api.hashes import ApiHashes
from app.lib.api.hashcat import ApiHashcat
from app.lib.api.wordlists import ApiWordlists
from app.lib.api.rules import ApiRules
from app.lib.api.mask import ApiMask
from app.lib.api.auth import ApiAuth
from app.lib.api.base import ApiBase
from flask_login import current_user


bp = Blueprint('api', __name__)


@bp.route('/swagger.yaml', methods=['GET'])
def swagger():
    base = ApiBase()
    data = base.get_swagger_file('v1')

    response = Response()
    response.headers.add('Content-Type', 'text/plain')
    response.data = data
    return response


@bp.route('/sessions', methods=['POST'])
def session_create():
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()

    if not auth.auth(True):
        return base.send_access_denied_response()

    return sessions.create(current_user.id, current_user.username)


@bp.route('/sessions', methods=['GET'])
def session_get_all():
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()

    if not auth.auth(True):
        return base.send_access_denied_response()

    return sessions.get_all(current_user.id)


@bp.route('/sessions/<int:session_id>', methods=['GET'])
def session_get(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return sessions.get(user_id=current_user.id, session_id=session_id)


@bp.route('/sessions/<int:session_id>/validate', methods=['GET'])
def session_validate(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return sessions.validate(current_user.id, session_id)


@bp.route('/sessions/<int:session_id>/state', methods=['GET'])
def session_state(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return sessions.state(current_user.id, session_id)


@bp.route('/sessions/<int:session_id>/termination', methods=['POST'])
def session_termination(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return sessions.termination(current_user.id, session_id)


@bp.route('/sessions/<int:session_id>/notifications', methods=['POST'])
def session_notifications(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return sessions.notifications(current_user.id, session_id)


@bp.route('/sessions/<int:session_id>/execute', methods=['POST'])
def session_action(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return sessions.action(current_user.id, session_id)


@bp.route('/hashes/<int:session_id>/upload', methods=['POST'])
def hashes_upload(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    hashes = ApiHashes()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return hashes.upload(current_user.id, session_id)


@bp.route('/hashes/remote', methods=['GET'])
def hashes_remote():
    auth = ApiAuth()
    base = ApiBase()
    hashes = ApiHashes()

    if not auth.auth(True):
        return base.send_access_denied_response()

    return hashes.get_remote()


@bp.route('/hashes/<int:session_id>/remote', methods=['POST'])
def hashes_remote_set(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    hashes = ApiHashes()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return hashes.set_remote(current_user.id, session_id)


@bp.route('/hashes/<int:session_id>/download', methods=['POST'])
def hashes_download(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    hashes = ApiHashes()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return hashes.download(current_user.id, session_id)


@bp.route('/hashcat/types', methods=['GET'])
def hashcat_types():
    auth = ApiAuth()
    base = ApiBase()
    hashcat = ApiHashcat()

    if not auth.auth(True):
        return base.send_access_denied_response()

    return hashcat.get_types()


@bp.route('/hashcat/<int:session_id>/type', methods=['POST'])
def hashcat_type_set(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    hashcat = ApiHashcat()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return hashcat.set_type(current_user.id, session_id)


@bp.route('/hashcat/<int:session_id>/optimise', methods=['POST'])
def hashcat_set_optimisation(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    hashcat = ApiHashcat()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return hashcat.set_optimisation(current_user.id, session_id)


@bp.route('/hashcat/<int:session_id>/mode', methods=['POST'])
def hashcat_set_mode(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    hashcat = ApiHashcat()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return hashcat.set_mode(current_user.id, session_id)


@bp.route('/mask/<int:session_id>', methods=['POST'])
def mask_set(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    mask = ApiMask()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return mask.set_mask(current_user.id, session_id)


@bp.route('/mask/<int:session_id>/increment', methods=['POST'])
def mask_increment_set(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    mask = ApiMask()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return mask.set_increment(current_user.id, session_id)


@bp.route('/wordlists', methods=['GET'])
def wordlists():
    auth = ApiAuth()
    base = ApiBase()
    wordlists = ApiWordlists()

    if not auth.auth(True):
        return base.send_access_denied_response()

    return wordlists.get()


@bp.route('/wordlists/<int:session_id>/type', methods=['POST'])
def wordlist_set_type(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    wordlists = ApiWordlists()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return wordlists.set_type(current_user.id, session_id)


@bp.route('/wordlists/<int:session_id>/global', methods=['POST'])
def wordlist_set_global(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    wordlists = ApiWordlists()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return wordlists.set_global(current_user.id, session_id)


@bp.route('/wordlists/<int:session_id>/custom', methods=['POST'])
def wordlist_set_custom(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    wordlists = ApiWordlists()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return wordlists.set_custom(current_user.id, session_id)


@bp.route('/wordlists/<int:session_id>/cracked', methods=['POST'])
def wordlist_set_cracked(session_id):
    auth = ApiAuth()
    base = ApiBase()
    sessions = ApiSession()
    wordlists = ApiWordlists()

    if not auth.auth(True):
        return base.send_access_denied_response()
    elif not sessions.can_access(current_user, session_id):
        return base.send_access_denied_response()

    return wordlists.set_cracked(current_user.id, session_id)


@bp.route('/rules', methods=['GET'])
def rules():
    auth = ApiAuth()
    base = ApiBase()
    rules = ApiRules()

    if not auth.auth(True):

app/controllers/config/__init__.py
from flask import Blueprint

bp = Blueprint('config', __name__, url_prefix='/config')


from . import index
from .system import general, hashcat, webpush, ldap, azure, users, password_complexity, shell_logs, message, device_profiles
from .account import profile, theme, logins, api

app/lib/api/auth.py
from flask import request
from flask_login import login_user
from app.lib.models.api import ApiKeys
from app.lib.models.user import UserModel
from sqlalchemy import and_


class ApiAuth:
    def auth(self, auto_login_user):
        apikey = request.headers['X-CrackerJack-Auth'].strip() if 'X-CrackerJack-Auth' in request.headers else ''
        if len(apikey) == 0:
            return False

        user = self.__auth(apikey)
        if user is False:
            return False

        if auto_login_user:
            login_user(user)

        return True

    def __auth(self, apikey):
        if len(apikey) == 0:
            return False

        key = ApiKeys.query.filter(and_(ApiKeys.apikey == apikey, ApiKeys.enabled == True)).first()
        if not key:
            return False

        user = UserModel.query.filter(UserModel.id == key.user_id).first()
        if not user:
            return False

        return user

app/templates/config/account/api.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="row mt-5">
    <div class="col-lg-3">
        {% set active_nav = 'api' %}
        {% include 'config/includes/sidebar.html' %}
    </div>
    <div class="col-lg-6">
        <h4>API Keys</h4>

        <p><a href="{{ url_for('api.swagger') }}">For the Swagger 2.0 definition click here</a></p>
        <form method="post" action="{{ url_for('config.api_add') }}" autocomplete="off">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">

            <div class="row">
                <div class="col-9 form-group">
                    <input type="text" name="name" id="name" placeholder="key name - something unique" class="form-control" required autofocus>
                </div>
                <div class="col form-group">
                    <button type="submit" class="btn btn-primary btn-block">create</button>
                </div>
            </div>
        </form>

        <table class="table table-sm table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Key</th>
                <th class="text-center">Active</th>
            </tr>
            </thead>
            <tbody>
            {% set c = 0 %}
            {% for apikey in apikeys %}
                {% set c = c + 1 %}
            <tr>
                <td>{{ c }}</td>
                <td>{{ apikey.name }}</td>
                <td class="text-monospace">{{ apikey.apikey }}</td>
                <td class="text-center">
                    <form id="api-set-status" method="post" action="{{ url_for('config.api_set_status', key_id=apikey.id) }}" autocomplete="off">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        {% if apikey.enabled %}
                        <input type="hidden" name="action" value="disable">
                        <a href="#" class="api-set-status text-success" title="click to disable"><i class="fas fa-check"></i></a>
                        {% else %}
                        <input type="hidden" name="action" value="enable">
                        <a href="#" class="api-set-status text-danger" title="click to enable"><i class="fas fa-times"></i></a>
                        {% endif %}
                    </form>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('.api-set-status').click(function() {
            $('#api-set-status').submit();
            return false;
        });
    });
</script>
{% endblock %}

app/templates/config/account/logins.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="row mt-5">
    <div class="col-lg-3">
        {% set active_nav = 'logins' %}
        {% include 'config/includes/sidebar.html' %}
    </div>
    <div class="col-lg-6">
        <h4>Logins</h4>
        <table class="table table-sm table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Username</th>
                <th class="text-right">Date</th>
            </tr>
            </thead>
            <tbody>
            {% for login in logins %}
            <tr>
                <td>{{ login.id }}</td>
                <td>{{ login.username }}</td>
                <td class="text-right">{{ login.login_at.strftime('%Y-%m-%d %H:%M:%S') }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/config/account/profile.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="row mt-5">
    <div class="col-lg-3">
        {% set active_nav = 'profile' %}
        {% include 'config/includes/sidebar.html' %}
    </div>
    <div class="col-lg-6">
        <h4>Profile</h4>

        <form method="post" action="{{ url_for('config.profile_save', user_id=user.id) }}" autocomplete="off">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">

            <div class="form-group">
                <label for="existing_password">Existing Password</label>
                <input type="password" value="" name="existing_password" id="existing_password" class="form-control" required autofocus>
            </div>

            <div class="form-group">
                <label for="new_password">New Password</label>
                <input type="password" value="" name="new_password" id="new_password" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="confirm_password">Confirm Password</label>
                <input type="password" value="" name="confirm_password" id="confirm_password" class="form-control" required>
            </div>

            <button type="submit" class="btn btn-primary btn-block">save</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/config/account/theme.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="row mt-5">
    <div class="col-lg-3">
        {% set active_nav = 'theme' %}
        {% include 'config/includes/sidebar.html' %}
    </div>
    <div class="col-lg-6">
        <h4>Theme</h4>

        <form method="post" action="{{ url_for('config.theme_save') }}" autocomplete="off">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">

            <div class="form-group clearfix">
                <label for="theme">Theme</label>
                <select name="theme" id="theme" class="form-control custom-select">
                    <option value=""></option>
                    {% for name, theme in themes.items() %}
                    {% set t = name|replace('.css', '') %}
                    <option value="{{ t }}" {{ 'selected' if selected_theme == t else '' }}>{{ t }}</option>
                    {% endfor %}
                </select>
                <small class="font-italic float-right">themes are from <a href="https://bootswatch.com/">https://bootswatch.com/</a></small>
            </div>

            <button type="submit" class="btn btn-primary btn-block">save</button>
        </form>
    </div>
</div>
{% endblock %}