app/controllers/install.py
from flask import Blueprint
from flask import render_template, redirect, url_for, flash, request
from app.lib.base.provider import Provider


bp = Blueprint('install', __name__)


@bp.route('/', methods=['GET'])
def index():
    provider = Provider()
    users = provider.users()
    password_complexity = provider.password_complexity()

    if users.get_user_count() > 0:
        flash('Application has already been configured.', 'error')
        return redirect(url_for('home.index'))

    return render_template(
        'install/index.html',
        complexity=password_complexity.get_requirement_description()
    )


@bp.route('/save', methods=['POST'])
def save():
    provider = Provider()
    users = provider.users()

    if users.get_user_count() > 0:
        flash('Application has already been configured.', 'error')
        return redirect(url_for('home.index'))

    username = request.form['username'].strip()
    password = request.form['password'].strip()
    full_name = request.form['full_name'].strip()
    email = request.form['email'].strip()

    if len(username) == 0 or len(password) == 0 or len(full_name) == 0 or len(email) == 0:
        flash('Please fill in all the fields', 'error')
        return redirect(url_for('install.index'))

    if not users.save(0, username, password, full_name, email, 1, 0, 1):
        flash('Could not create user: ' + users.get_last_error(), 'error')
        return redirect(url_for('install.index'))

    flash('Please login as the newly created administrator', 'success')
    return redirect(url_for('home.index'))

app/templates/install/index.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="row mt-5">
    <div class="col-3"></div>
    <div class="col">
        <div class="card">
            <h3 class="card-header">CrackerJack Setup</h3>
            <div class="card-body">
                <form method="post" action="{{ url_for('install.save') }}" autocomplete="off">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">

                    <div class="form-group">
                        <label for="username">Administrator Username</label>
                        <input type="text" value="" name="username" id="username" class="form-control" placeholder="admin" required autofocus>
                    </div>

                    <div class="form-group">
                        <label for="password">
                            Administrator Password
                            <br>
                            <small><i>{{ complexity }}</i></small>
                        </label>
                        <input type="password" value="" name="password" id="password" class="form-control" placeholder="correct horse battery staple" required>
                    </div>

                    <div class="form-group">
                        <label for="full_name">Full Name</label>
                        <input type="text" value="" name="full_name" id="full_name" class="form-control" placeholder="Admin User" required>
                    </div>

                    <div class="form-group">
                        <label for="email">E-Mail</label>
                        <input type="text" value="" name="email" id="email" class="form-control" placeholder="you@yourdomain.com" required>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">setup</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}